name: Release APK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag para la release (ej: v1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for scripts
        run: |
          chmod +x build-apk.sh

      - name: Build APK using script
        run: ./build-apk.sh

      - name: Create APK filename
        run: echo "APK_FILENAME=salva-roberto-${{ github.event.inputs.tag }}.apk" >> $GITHUB_ENV

      - name: Rename APK
        run: |
          cp app-debug.apk ${{ env.APK_FILENAME }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.APK_FILENAME }}
          asset_name: ${{ env.APK_FILENAME }}
          asset_content_type: application/vnd.android.package-archive 